run:
	python3 trans.py ../../data/ncl_mac.v ../../data/result
	python3 dft_trace.py ../../data/result ../../data/pathlog.txt

clean:
	rm -rf __pycache__ *.pyc *.out test/__pycache__ test/*.pyc test/*.out
